"""One-time setup for self-hosted Langfuse tracing.  Run:  python scripts/setup_langfuse.py

1. Generates observability/langfuse.env (DB password, auth secrets, API keys, dashboard login) if absent.
2. Writes LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY / LANGFUSE_HOST into the project .env.
3. Starts Langfuse + its Postgres with docker compose and waits until the API answers.

Safe to re-run: existing secrets are kept, so keys and the dashboard login never change underneath you.
"""
from __future__ import annotations
import re, secrets, subprocess, sys, time, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LF_ENV = ROOT / "observability" / "langfuse.env"
COMPOSE = ROOT / "observability" / "docker-compose.langfuse.yml"
APP_ENV = ROOT / ".env"
HOST = "http://localhost:3000"


def read_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return dict(re.findall(r"^([A-Z_]+)=(.*)$", path.read_text(), flags=re.M))


def ensure_langfuse_env() -> dict[str, str]:
    env = read_env(LF_ENV)
    if env.get("LANGFUSE_PUBLIC_KEY"):
        return env
    env = {
        "LANGFUSE_DB_PASSWORD": secrets.token_urlsafe(24),
        "LANGFUSE_NEXTAUTH_SECRET": secrets.token_urlsafe(32),
        "LANGFUSE_SALT": secrets.token_urlsafe(32),
        "LANGFUSE_ENCRYPTION_KEY": secrets.token_hex(32),          # 64 hex chars, as Langfuse requires
        "LANGFUSE_PUBLIC_KEY": "pk-lf-" + secrets.token_hex(16),
        "LANGFUSE_SECRET_KEY": "sk-lf-" + secrets.token_hex(16),
        "LANGFUSE_ADMIN_EMAIL": "admin@closefuture.local",
        "LANGFUSE_ADMIN_PASSWORD": secrets.token_urlsafe(12),
    }
    LF_ENV.write_text("# generated by scripts/setup_langfuse.py - keep private (git-ignored)\n"
                      + "".join(f"{k}={v}\n" for k, v in env.items()))
    print(f"created {LF_ENV.relative_to(ROOT)}")
    return env


def wire_app_env(env: dict[str, str]) -> None:
    text = APP_ENV.read_text()
    for key, value in {"LANGFUSE_PUBLIC_KEY": env["LANGFUSE_PUBLIC_KEY"],
                       "LANGFUSE_SECRET_KEY": env["LANGFUSE_SECRET_KEY"],
                       "LANGFUSE_HOST": HOST}.items():
        if re.search(rf"^{key}=.*$", text, flags=re.M):
            text = re.sub(rf"^{key}=.*$", f"{key}={value}", text, flags=re.M)
        else:
            text = text.rstrip("\n") + f"\n{key}={value}\n"
    APP_ENV.write_text(text)
    print("wired Langfuse keys into .env")


def start_and_wait() -> None:
    subprocess.run(["docker", "compose", "-f", str(COMPOSE), "--env-file", str(LF_ENV), "up", "-d"], check=True)
    print("waiting for Langfuse to answer", end="", flush=True)
    for _ in range(90):
        try:
            with urllib.request.urlopen(f"{HOST}/api/public/health", timeout=3) as r:
                if r.status == 200:
                    print(" - ready")
                    return
        except Exception:
            pass
        print(".", end="", flush=True)
        time.sleep(2)
    sys.exit("\nLangfuse did not become healthy - check: docker compose -f observability/docker-compose.langfuse.yml logs")


if __name__ == "__main__":
    env = ensure_langfuse_env()
    wire_app_env(env)
    start_and_wait()
    print(f"\nDashboard: {HOST}\nLogin:     {env['LANGFUSE_ADMIN_EMAIL']} / {env['LANGFUSE_ADMIN_PASSWORD']}"
          "\nRestart the API so it starts sending traces.")
